recipes/urls.py
from django.urls import include, path
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('rest/', include('recipes_rest.urls')),
    path('admin/', admin.site.urls),
    path('', include('recipes_site.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

recipes_rest/urls.py
from django.urls import re_path, include
from rest_framework import routers
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView, TokenVerifyView

from recipes_rest.views import *

router = routers.DefaultRouter()
router.register(r'recipes', RecipeViewSet, basename='recipe')
router.register(r'quantities', QuantityViewSet, basename='quantity')
router.register(r'ingredients', IngredientViewSet, basename='ingredient')
router.register(r'users', UserViewSet, basename='user')
router.register(r'categories', CategoryViewSet, basename='category')
router.register(r'moments', MomentViewSet, basename='moment')
router.register(r'profile', ProfileViewSet, basename='profile')
router.register(r'ownedRecipes', OwnedRecipeViewSet, basename='owned-recipes')
router.register(r'times', TimeUnitViewSet, basename='times')
router.register(r'recipeQuantities', RecipeIngredients, basename='recipe_quantities')
router.register(r'foodPlanning', FoodPlanViewSet, basename='food_plan')

small_router = routers.DefaultRouter()
small_router.register(r'recipes', SmallRecipesViewSet, basename='small-recipe')
small_router.register(r'moments', SmallMomentViewSet, basename='small-moment')

urlpatterns = [
    re_path(r'^', include(router.urls)),
    re_path(r'^small/', include(small_router.urls)),
    re_path(r'^upload/$', UploadView.as_view(), name='add-recipe'),
    re_path(r'^myProfile/', MyProfileView.as_view({'get': 'retrieve', 'post': 'update', 'patch': 'partial_update'}), name='my-profile'),
    re_path(r'^recipeIngredients/(?P<recipe_id>[0-9]+)/', RecipeIngredients.as_view({'get': 'list'}), name='recipe-ingredients'),
    re_path(r'^api-token-auth/', TokenObtainPairView.as_view(), name='api_token_auth'),
    re_path(r'^api-token-verify/', TokenVerifyView.as_view()),
    re_path(r'^api-token-refresh/', TokenRefreshView.as_view()),
]

recipes_site/urls.py
from django.urls import re_path
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static

from recipes_site import views


app_name = "recipes_site"
urlpatterns = static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + [
    re_path(r'^ngsw-worker.js', TemplateView.as_view(
        template_name="recipes_site/ngsw-worker.js",
        content_type='application/javascript',
    ), name='ngsw-worker.js'),
    re_path(r'^ngsw.json', TemplateView.as_view(
        template_name="recipes_site/ngsw.json",
        content_type='application/json',
    ), name='ngsw-worker.js'),
    re_path(r'^$', views.index),
    re_path(r'^recipe/[0-9]*$', views.index),
    re_path(r'^search/[0-9]*$', views.index),
    re_path(r'^login$', views.index),
    re_path(r'^register$', views.index),
    re_path(r'^createRecipe$', views.index),
]

recipes_site/models.py
from django.db import models

# Create your models here.

recipes_site/forms.py
from django.contrib.auth.forms import UserChangeForm


class EditUserForm(UserChangeForm):
    pass

recipes_site/views.py
from django.shortcuts import render, redirect, reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.http import JsonResponse
from django.views.generic import FormView
from django.contrib.auth import login
from django.contrib.auth.models import User

from bs4 import BeautifulSoup
import requests
import json

from recipes_models.models import Profile, Recipe, Category, Ingredient, DisplayType, FoodPlanning
from recipes_site.forms import EditUserForm


def index(request, *args, **kwargs):
    return render(request, 'recipes_site/index.html')


def file_view(request, filename):
    return render(request, 'recipes_site/' + filename)


@login_required
def create_recipe(request):
    return render(request, 'recipes_site/addRecipe.html')


@login_required
def import_recipe(request):
    return render(request, 'recipes_site/addIcaRecipe.html')


@login_required
def category(request, category):
    context = {
        'category': category
    }
    return render(request, 'recipes_site/category.html', context=context)


@login_required
def recipe_import(request, id):
    result = requests.get("https://handla.api.ica.se/api/recipes/recipe/{0}/".format(id), headers={'Accept': 'application/json'})
    json = result.json()
    for i, val in enumerate(json['CookingSteps']):
        json['CookingSteps'][i] = BeautifulSoup(val, "html.parser").text
    return JsonResponse(json)


@login_required
def event_planning(request, id):
    context = {
        'week_plan': FoodPlanning.objects.get(id=id)
    }
    return render(request, 'recipes_site/foodPlanning.html', context=context)


@login_required
def change_favorite(request):
    body = json.loads(request.body)
    recipe = Recipe.objects.get(id=body['recipe'])
    profile = Profile.objects.get(user=request.user)
    if body['favorite']:
        profile.favorite_recipes.add(recipe)
    else:
        profile.favorite_recipes.remove(recipe)
    profile.save()
    return JsonResponse({})


@login_required
def create_food_plan(request):
    return render(request, 'recipes_site/createFoodPlanning.html')


def recipe(request, id):
    if request.user.is_authenticated:
        (profile, _) = Profile.objects.get_or_create(user=request.user)
        recipes = profile.favorite_recipes.all() | Recipe.objects.filter(creator=request.user).distinct()
    else:
        recipes = []
        profile = None
    context = {
        'recipe_list': recipes,
        'display_types': [enum for enum in DisplayType],
        'profile': profile,
        'recipe': '/rest/recipes/{0}'.format(id)
    }
    return render(request, 'recipes_site/index.html', context)


class RegisterView(FormView):
    template_name = 'registration/register.html'
    form_class = UserCreationForm

    def get_success_url(self):
        return reverse('recipes_site.index')

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('recipes_site:index')
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        login(self.request, form.save())
        return super().form_valid(form)


class EditUserView(FormView):
    template_name = 'recipes_site/profile.html'
    form_class = EditUserForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['user'] = self.request.user
        context['display_types'] = (value for _, value in DisplayType.__members__.items())
        return context

recipes_site/templates/recipes_site/addIcaRecipe.html
{% extends 'recipes_site/template.html' %}
{% load static %}
{% load i18n %}

{% block extra_head %}
    <link href="{% static 'recipes_site/css/component.css' %}" rel="stylesheet" />
{% endblock %}

{% block content %}

    <div id="import"></div>

{% endblock %}

{% block scripts %}
    <script src="{% static 'recipes_site/js/bundle.js' %}"></script>
    <script src="{% static 'recipes_site/js/custom-file-input.js' %}"></script>
    <script src="{% static 'recipes_site/js/addRecipe.js' %}"></script>
    <script>
        $(document).ready(function () {
            renderImportRecipe(document.getElementById('import'));
        });


    </script>
{% endblock %}

recipes_site/templates/recipes_site/addRecipe.html
{% extends 'recipes_site/template.html' %}
{% load static %}
{% load i18n %}

{% block extra_head %}
    <link href="{% static 'recipes_site/css/component.css' %}" rel="stylesheet" />
{% endblock %}

{% block content %}
    <div id="recipeForm"></div>
{% endblock %}

{% block scripts %}
    <script src="{% static 'recipes_site/js/bundle.js' %}"></script>
    <script src="{% static 'recipes_site/js/custom-file-input.js' %}"></script>
    <script src="{% static 'recipes_site/js/addRecipe.js' %}"></script>

    <script>
        $(document).ready(function () {
            renderAddRecipe(document.getElementById('recipeForm'));
        });
    </script>
{% endblock %}

recipes_site/templates/recipes_site/category.html
{% extends 'recipes_site/template.html' %}

{% load i18n %}
{% load static %}

{% block extra_scripts %}
    <script src="{% static 'recipes_site/js/bundle.js' %}"></script>
    <script>
        const SEARCH_DATA = {};
        SEARCH_DATA.category = "{{ category }}";
        SEARCH_DATA.favoured_by = "{{ user.id }}";
        $(document).ready(function () {
            renderSearchPage(document.getElementById("container"))
        });
    </script>
{% endblock %}

recipes_site/templates/recipes_site/createFoodPlanning.html
{% extends 'recipes_site/template.html' %}
{% load static %}
{% load i18n %}

{% block content %}
    <div id="planning"></div>
{% endblock %}
{% block scripts %}
    <script src="{% static 'recipes_site/js/bundle.js' %}"></script>
    <script>
        $(document).ready(function () {
            renderPlanningForm(document.getElementById('planning'));
        });
    </script>
{% endblock %}

recipes_site/templates/recipes_site/foodPlanning.html
{% extends 'recipes_site/template.html' %}
{% load static %}
{% load i18n %}

{% block content %}

    <div id="modal"></div>
{% endblock %}
{% block scripts %}
    <script src="{% static 'recipes_site/js/bundle.js' %}"></script>
    <script>
        $(document).ready(function () {
            renderFoodPlanTable(document.getElementById("modal"));
        });
    </script>
{% endblock %}

recipes_site/templates/recipes_site/profile.html
{% extends 'recipes_site/template.html' %}
{% load i18n %}
{% load static %}

{% block extra_head %}
    <link href="{% static 'recipes_site/css/register.css' %}" rel="stylesheet"/>
{% endblock %}
{% block content %}
    <form class="needs-validation" class="form-signin" method="post" novalidate>
        {% csrf_token %}
        <h2 class="form-signin-heading">{% trans 'Edit user' %}</h2>
        <div class="my-2">
            <label for="email">{% trans 'Email' %}</label>
            <input type="email" value="{% if form.data.email %}{{ form.data.email }}{% else %}{{ user.email }}{% endif %}" id="email" name="email"
                   class="form-control rounded mb-2{% if form.email.errors %} is-invalid{% endif %}"
                   placeholder="{% trans 'Email' %}" required autofocus>
            <div class="invalid-feedback">
                {% if form.email.errors %}
                    {% for error in form.email.errors %}
                        <div>{{ error }}</div>
                    {% endfor %}
                {% endif %}
            </div>
        </div>
        <div class="my-2">
            <label for="oldPassword">{% trans 'Old Password' %}</label>
            <input type="password" id="oldPassword" name="oldPassword" class="form-control rounded mb-2{% if form.password1.errors %} is-invalid{% endif %}" placeholder="{% trans 'Password' %}" required>
            <div class="invalid-feedback">
                {% if form.password1.errors %}
                    {% for error in form.password1.errors %}
                        <div>{{ error }}</div>
                    {% endfor %}
                {% endif %}
            </div>
        </div>
        <div class="my-2">
            <label for="newPassword">{% trans 'New Password' %}</label>
            <input type="password" id="newPassword" name="newPassword" class="form-control rounded mb-2{% if form.password1.errors %} is-invalid{% endif %}" placeholder="{% trans 'Password' %}" required>
            <div class="invalid-feedback">
                {% if form.password1.errors %}
                    {% for error in form.password1.errors %}
                        <div>{{ error }}</div>
                    {% endfor %}
                {% endif %}
            </div>
        </div>
        <div class="my-2">
            <label for="confirmPassword">{% trans 'Confirm password' %}</label>
            <input type="password" id="confirmPassword" name="confirmPassword" class="form-control rounded{% if form.password2.errors %} is-invalid{% endif %}" placeholder="{% trans 'Password' %}" required>
            <div class="invalid-feedback">
                {% if form.password2.errors %}
                    {% for error in form.password2.errors %}
                        <div>{{ error }}</div>
                    {% endfor %}
                {% endif %}
            </div>
        </div>
        <button class="btn btn-lg btn-primary btn-block my-1" type="submit">{% trans 'Save' %}</button>
    </form>
{% endblock %}

{% block scripts %}
    <script src="{% static 'recipes_site/js/formValidation.js' %}"></script>
{% endblock %}

recipes_site/templates/recipes_site/template.html
{% load static %}
{% load i18n %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Magnus receptsite">
    <meta name="author" content="">
    <link rel="manifest" href="{% url 'recipes_site:manifest' %}">
    <link rel="icon" href="{% static 'recipes_site/images/../../recipes/src/assets/images/logo.png' %}">
    <meta name="theme-color" content="darkblue">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'recipes_site/images/../../recipes/src/assets/images/iphone-logo.png' %}">
	<meta name="apple-mobile-web-app-status-bar-style" content="default">

    <title>Recipes</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link href="{% static 'recipes_site/css/default.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">

    <style>
        .navbar {
            background-color: darkblue;
        }
    </style>
    {% block extra_head %}{% endblock %}

</head>

<body>
<nav class="navbar navbar-expand-md navbar-dark fixed-top">
    <a class="navbar-brand" href="{% url 'recipes_site:index' %}"><img style="height: 30px" src="{% static 'recipes_site/images/../../recipes/src/assets/images/logo.png' %}" alt="home"/></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon" />
    </button>

    <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <div class="dropdown">
            <button class="btn btn-outline-light dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                {% trans "Recipes" %}
            </button>
            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                {% for category in categories %}
                    {% trans category.name as name %}
                    <a class="dropdown-item" href="{% url 'recipes_site:category' category=category.id %}">{% blocktrans %}Your {{ name }}{% endblocktrans %}</a>
                {% endfor %}
            </div>
        </div>
        <form class="form-inline my-2 my-lg-0 ml-auto" action="{% url 'recipes_site:search' %}">
            <input name="q" class="form-control mr-sm-2" type="text" placeholder="{% trans "Search" %}" aria-label="Search">
            <button class="btn btn-light my-2 my-sm-0" type="submit">{% trans "Search" %}</button>
        </form>
        {% if user.is_authenticated  %}
            <a href="{% url 'recipes_site:edit-user' %}" class="btn btn-outline-light ml-1" role="button">{% trans 'Profile' %}</a>
            <a href="{% url 'recipes_site:create-food-planning' %}" class="btn btn-outline-light ml-1" role="button">{% trans 'Create planning' %}</a>
            <a href="{% url 'recipes_site:add-recipe' %}" class="btn btn-outline-light ml-1" role="button">{% trans 'Create recipe' %}</a>
            <a href="{% url 'recipes_site:logout' %}" class="btn btn-outline-light ml-1" role="button">{% trans 'Logout' %}</a>
        {% else %}
            <a href="{% url 'recipes_site:login' %}" class="btn btn-outline-light ml-1" role="button">{% trans 'Login' %}</a>
            <a href="{% url 'recipes_site:register' %}" class="btn btn-outline-light ml-1" role="button">{% trans 'Register' %}</a>
        {% endif %}
    </div>
</nav>
<div id="banner" class="mb-3" style="visibility: hidden">{% block banner_text %}{% endblock %}</div>
<main role="main" class="container" id="container">
    {% block content %}
    {% endblock %}
</main>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<script src="{% static 'recipes_site/js/script.js' %}"></script>
<script>

    $.ajaxSetup({
        beforeSend: function(xhr, settings) {
            if (!/^(GET|HEAD|OPTIONS|TRACE)$/i.test(settings.type) && !this.crossDomain) {
                xhr.setRequestHeader("X-CSRFToken", "{{ csrf_token }}");
            }
        }
    });

    $(document).ajaxError(function(event, jqXHR) {
        if(jqXHR.status === 403) {
            window.location = "{% url 'recipes_site:login' %}?next=" + window.location.pathname;
        }
    });
    {% if recipe %}
        const ACTIVE_RECIPE = '{{ recipe }}';
    {% else %}
        const ACTIVE_RECIPE = null;
    {% endif %}

</script>
{% block scripts %}{% endblock %}
{% block extra_scripts %}{% endblock %}
<script src="{% static 'recipes_site/js/bundle.js' %}"></script>
</body>
</html>